name: build

on:
  push:
    branches: [ develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  # This initial job will determine if the current commit already has a tag
  # to avoid running duplicate workflows
  check-conditions:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      has_tag: ${{ steps.check.outputs.has_tag }}
      tag_name: ${{ steps.check.outputs.tag_name }}
      version: ${{ steps.check.outputs.version }}
      is_develop: ${{ steps.check.outputs.is_develop }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to properly check tags
    
    - name: Check if we should run this workflow
      id: check
      run: |
        # Check if this is a develop branch build
        IS_DEVELOP=false
        if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          IS_DEVELOP=true
        fi
        echo "is_develop=$IS_DEVELOP" >> $GITHUB_OUTPUT
        
        # If this is a pull request or manual trigger, always run
        if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "has_tag=false" >> $GITHUB_OUTPUT
          echo "tag_name=" >> $GITHUB_OUTPUT
          echo "version=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # If this is a tag push directly, always run
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "has_tag=true" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # If this is a develop branch push, we should run the workflow
        if [[ "$IS_DEVELOP" == "true" ]]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "has_tag=false" >> $GITHUB_OUTPUT
          echo "tag_name=" >> $GITHUB_OUTPUT
          echo "version=$(date +'%Y.%m.%d')-dev" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # If this is a branch push (master/main), check if this commit already has a tag
        COMMIT_SHA="${{ github.sha }}"
        TAG_AT_COMMIT=$(git tag --points-at $COMMIT_SHA)
        
        if [[ -n "$TAG_AT_COMMIT" && "$TAG_AT_COMMIT" == v* ]]; then
          # This commit already has a version tag - should only build in response to the tag
          echo "should_run=true" >> $GITHUB_OUTPUT
          echo "has_tag=true" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_AT_COMMIT" >> $GITHUB_OUTPUT
          echo "version=${TAG_AT_COMMIT#v}" >> $GITHUB_OUTPUT
        else
          # No tag, and it's not develop branch - we should NOT run the workflow
          echo "should_run=false" >> $GITHUB_OUTPUT
          echo "has_tag=false" >> $GITHUB_OUTPUT
          echo "tag_name=" >> $GITHUB_OUTPUT
          echo "version=0.0.0" >> $GITHUB_OUTPUT
        fi

  build-windows:
    needs: check-conditions
    if: needs.check-conditions.outputs.should_run == 'true'
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2exe
        pip install -r requirements.txt
      
    - name: Build Windows executable
      run: |
        python build_win.py --clean
      env:
        POLARS_SKIP_CPU_CHECK: 1
        CI_VERSION: ${{ needs.check-conditions.outputs.version }}
      
    - name: List build artifacts
      run: |
        echo "Contents of dist directory:"
        dir dist
        echo "Contents of release_artifacts directory:"
        dir release_artifacts
      
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: release_artifacts/*.exe
        retention-days: 7
  
  build-macos:
    needs: check-conditions
    if: needs.check-conditions.outputs.should_run == 'true'
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install pillow
        pip install -r requirements.txt
      
    - name: Print system information
      run: |
        echo "macOS version: $(sw_vers -productVersion)"
        echo "Architecture: $(uname -m)"
        python -c "import platform; print(f'Python architecture: {platform.machine()}')"
      
    - name: Build macOS application
      run: |
        python build_mac.py clean py2app
      env:
        CI_VERSION: ${{ needs.check-conditions.outputs.version }}
      
    - name: Check app bundle
      run: |
        echo "Contents of dist directory:"
        ls -la dist/
        echo "Looking for .app directories:"
        find dist -name "*.app" -type d
        
        echo "Contents of release_artifacts directory:"
        ls -la release_artifacts/
        
        # Verify the app bundle structure in release_artifacts
        APP_PATH=$(find release_artifacts -name "*.app" -type d | head -1)
        if [ -n "$APP_PATH" ]; then
          echo "Checking app bundle structure for $APP_PATH"
          ls -la "$APP_PATH/Contents/MacOS/"
          if [ ! -f "$APP_PATH/Contents/MacOS/"* ]; then
            echo "ERROR: No executable found in MacOS directory!"
            exit 1
          else
            echo "App bundle structure looks good!"
          fi
        else
          echo "No .app bundle found in release_artifacts!"
          exit 1
        fi
      
    - name: Upload macOS app bundle
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: release_artifacts/*.app
        retention-days: 7

  create-source-code-zip:
    name: Create Source Code Package
    needs: check-conditions
    if: needs.check-conditions.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create source code zip
      run: |
        # Create a directory for the source code
        mkdir -p source-code
        
        # Copy all files except excluded ones
        rsync -av --exclude='.git' --exclude='venv' --exclude='__pycache__' \
              --exclude='build' --exclude='dist' --exclude='logs' \
              --exclude='.DS_Store' --exclude='*.pyc' \
              . source-code/
        
        # Create the zip file
        cd source-code
        zip -r ../SourceCode.zip .
        cd ..
        
        echo "Created source code zip:"
        ls -la SourceCode.zip
    
    - name: Upload source code zip
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: SourceCode.zip
        retention-days: 7

  # This job creates a GitHub release with all artifacts when a tag is pushed
  create-release:
    name: Create Release
    needs: [check-conditions, build-windows, build-macos, create-source-code-zip]
    # Run this job if a tag is present or on manual trigger, but not for develop branch
    if: (needs.check-conditions.outputs.has_tag == 'true' || github.event_name == 'workflow_dispatch') && needs.check-conditions.outputs.is_develop != 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags for generating release notes
      
      - name: Extract version
        id: get_version
        run: |
          if [[ "${{ needs.check-conditions.outputs.has_tag }}" == "true" ]]; then
            VERSION="${{ needs.check-conditions.outputs.version }}"
            TAG_VERSION="${{ needs.check-conditions.outputs.tag_name }}"
            IS_DRAFT=false
          else
            VERSION="${{ needs.check-conditions.outputs.version }}"
            TAG_VERSION="build-$VERSION"
            IS_DRAFT=true
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "IS_DRAFT=$IS_DRAFT" >> $GITHUB_OUTPUT
          
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
          
      - name: Prepare artifacts for release
        run: |
          mkdir -p release-artifacts
          
          # Rename artifacts with version number
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          
          # Windows executable
          echo "Preparing Windows executable..."
          # Find and copy the Windows executable
          find all-artifacts/windows-exe -name "*.exe" -type f -exec cp {} release-artifacts/KPAstrologyDashboard-${VERSION}-Windows.exe \; || echo "No Windows executable found"
          
          # macOS app
          echo "Preparing macOS app..."
          # Find and copy the macOS app bundle
          mkdir -p release-artifacts/tmp
          find all-artifacts/macos-app -name "*.app" -type d -exec cp -r {} release-artifacts/tmp/ \; || echo "No macOS app bundle found"
          # Rename the app bundle
          FOUND_APP=$(find release-artifacts/tmp -name "*.app" -type d | head -1)
          if [ -n "$FOUND_APP" ]; then
            APP_NAME=$(basename "$FOUND_APP")
            mkdir -p "release-artifacts/KPAstrologyDashboard-${VERSION}-macOS.app"
            cp -r "$FOUND_APP/"* "release-artifacts/KPAstrologyDashboard-${VERSION}-macOS.app/"
            # Clean up
            rm -rf release-artifacts/tmp
          fi
          
          # Source code ZIP
          echo "Preparing source code ZIP..."
          find all-artifacts/source-code -name "*.zip" -type f -exec cp {} release-artifacts/SourceCode-${VERSION}.zip \; || echo "No source code ZIP found"
          
          # List what we've collected
          echo "Contents of release-artifacts directory:"
          ls -la release-artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: KP Astrology Dashboard ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.TAG_VERSION }}
          draft: ${{ steps.get_version.outputs.IS_DRAFT }}
          prerelease: false
          generate_release_notes: true  # Automatically generate notes based on commits
          files: |
            release-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 