name: Build Windows Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
      
    - name: Build Windows executable
      run: |
        python build.py --target-platform windows --target-arch x64 --onefile --clean
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kp-dashboard-windows
        path: |
          dist/*.exe
          dist/KPAstrologyDashboard-*.zip
        retention-days: 7
        
    - name: Create release if tagged
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.exe
          dist/KPAstrologyDashboard-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 